### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by tracyrankin** [claudiopro/resume#4]
- Picture.  If you want to use this a primary source for your resume, you should update your picture.
- Make sure this information is matching your linkedIn account
- You are not listing java anywhere in your common UI info....you are only hinting to the UI pieces.
- Common UI, it doesn't give the sense that you were setting the technical direction for the whole product, sounds like it was just for the current team.
- I would make sure the job responsibility part came before what you did specifically for the team.  It needs to be more predominant.

**Comment by claudiopro** [comment]
@tracyrankin thanks Tracy! I'll make sure this is addressed :bow:

**Comment by claudiopro** [comment]
Addressed by 37af605.
